baseURL = 'http://stevebennett.co/'
languageCode = 'en-gb'
title = 'Thoughts on Engineering Management'

googleAnalytics = 'G-9255WBFQQM'

[social]
github = 'https://github.com/stebennett'
twitter = 'https://twitter.com/stevebennett'
linkedin = 'https://www.linkedin.com/in/stebennett/'
mastodon = 'https://engmanager.space/@steve'

[module]
[[module.imports]]
  path = 'github.com/stebennett/stevebennett-theme'

