baseURL = 'http://stevebennett.co/'
languageCode = 'en-gb'
title = 'Thoughts on Engineering Management'

googleAnalytics = 'G-9255WBFQQM'

[params.social]
github = 'https://github.com/stebennett'
twitter = 'https://twitter.com/stevebennett'
linkedin = 'https://www.linkedin.com/in/stebennett/'
mastodon = 'https://mastodon.me.uk/@steve'

[module]
[[module.imports]]
  path = 'github.com/stebennett/stevebennett-theme'

[[module.imports]]
  path = 'github.com/stebennett/notes'

  [[module.imports.mounts]]
  source = 'public_notes'
  target = 'content/notes'
  
[[permalinks]]
  notes = "/notes/:year/:month/:day/:slug/"
  posts = "/posts/:slug/"
