baseURL = 'https://stevebennett.co/'
languageCode = 'en-gb'
title = 'Steve Bennett - Engineering Leader'
googleAnalytics = 'G-9255WBFQQM'

[params]
name = 'Steve Bennett'
tagline = 'Engineering Leader'
shortBio = 'Engineering leader with over 15 years of experience in engineering management, with a background in eCommerce, enterprise services, and fintech. I aim to empower teams to create innovative and scalable solutions that enhance the customer experience and drive business value.'

[params.social]
github = 'https://github.com/stebennett'
twitter = 'https://twitter.com/stevebennett'
linkedin = 'https://www.linkedin.com/in/stebennett/'
mastodon = 'https://mastodon.me.uk/@steve'

[params.contentTypes]
[params.contentTypes.titles]
posts = "Writing"

[[permalinks]]
  posts = "/posts/:slug/"

[build]
  [build.buildStats]
    enable = true
