baseURL = 'http://stevebennett.co/'
languageCode = 'en-gb'
title = 'Steve Bennett - Engineering Leader'
googleAnalytics = 'G-9255WBFQQM'

[params]
name = 'Steve Bennett'
tagline = 'Engineering Leader'
shortBio = 'Engineering leader with over 15 years of experience in engineering management, with a background in eCommerce, enterprise services, and fintech. I aim to empower teams to create innovative and scalable solutions that enhance the customer experience and drive business value.'
tabsHeading = 'Work History'
twoBoxHeading = 'Community'

[params.social]
github = 'https://github.com/stebennett'
twitter = 'https://twitter.com/stevebennett'
linkedin = 'https://www.linkedin.com/in/stebennett/'
mastodon = 'https://mastodon.me.uk/@steve'


[module]
[[module.imports]]
  path = 'github.com/stebennett/stevebennett-theme'

[[module.imports]]
  path = 'github.com/stebennett/notes'

  [[module.imports.mounts]]
  source = 'public_notes'
  target = 'content/notes'
  
[[permalinks]]
  notes = "/notes/:year/:month/:day/:slug/"
  posts = "/posts/:slug/"
